### PR TITLE
:sparkles: feat(*): reuse angular rules as base and add emojis over it

### PR DESCRIPTION
**Pull request by jimmyfortinx**
Instead of creating and maintaining our own changelog style we could reuse the angular one and just add emojis support over it.

By doing that we loss commit grouped by scope, but the rest should be better (like working bitbucket repo links, breaking changes, revert, and much more). To get groups back we would need to overwrite the `commit.hbs` file by our own. This imply that we could loss some futur fixes since we will no more use the original template file.

There is an example of the style changes:

**Previous changelog**

```
<a name="1.0.3"></a>
# :gem: [1.0.3](http://my-bitbucket-repo///compare/v1.0.2...v1.0.3) fearful-sand (2018-02-19) :gem:

### :sparkles: Features :sparkles:
  **:**
  * random commit ([af38913](http://my-bitbucket-repo///commits/af38913))

  **stuff:**
  * something new ([7fd2e68](http://my-bitbucket-repo///commits/7fd2e68))
  * other new thing ([7fd2e69](http://my-bitbucket-repo///commits/7fd2e69))
```

<a name="1.0.3"></a>
# :gem: [1.0.3](http://my-bitbucket-repo///compare/v1.0.2...v1.0.3) fearful-sand (2018-02-19) :gem:

### :sparkles: Features :sparkles:
  **:**
  * random commit ([af38913](http://my-bitbucket-repo///commits/af38913))

  **stuff:**
  * something new ([7fd2e68](http://my-bitbucket-repo///commits/7fd2e68))
  * other new thing ([7fd2e69](http://my-bitbucket-repo///commits/7fd2e69))

**New changelog**

```
<a name="1.0.3"></a>
## [1.0.3](http://my-bitbucket-repo/~user/repo/compare/v1.0.2...v1.0.3) (2018-02-19)

### Features
  * random commit ([af38913](http://my-bitbucket-repo/~user/repo/commits/af38913))
  * **stuff:** something new ([7fd2e68](http://my-bitbucket-repo/~user/repo/commits/7fd2e68))
  * **stuff:** other new thing ([7fd2e69](http://my-bitbucket-repo/~user/repo/commits/7fd2e69))
```

<a name="1.0.3"></a>
### Features
  * random commit ([af38913](http://my-bitbucket-repo/~user/repo/commits/af38913))
  * **stuff:** something new ([7fd2e68](http://my-bitbucket-repo/~user/repo/commits/7fd2e68))
  * **stuff:** other new thing ([7fd2e69](http://my-bitbucket-repo/~user/repo/commits/7fd2e69))

### CODE REVIEW

**Comment by mlarose** [comment]
nice. for the benefit of other reviewers, by reusing he means inheritance instead of forking. 

about losing commit grouping by scope, can you expand on what, why and if you see a solution in a future PR or not.

**Review by mlarose — APPROVED** [review]

**Comment by jimmyfortinx** [comment]
@mlarose I edited the original comment to reflect your comment. Thanks for the feedback.

**Comment by jpatovh** [comment]
Nice.
if I understand well: this is just an improvement for the deprecated one?
From now, we'll not use this repo anymore, we'll use the offichal angular?

**Comment by antleblanc** [comment]
I close it for inactivity, but feel free to re-open it if needed.

**Pull request closed without merging**
